### PR TITLE
Update entry point for the Java testcode

### PR DESCRIPTION
**Pull request by sefroberg**

### CODE REVIEW

**Comment by sefroberg** [comment]
This merge request is dependent on the accompanying code in the internal gitlab repo to be merged as well. This will happen next week once @phracek has had a chance to review this change. 
I manually ran this on my Fedora 37 vm running a java 17 test run and it ran successfully.

**Comment by phracek** [comment]
[test]

**Review by phracek — CHANGES_REQUESTED** [review]
Sorry, where is a `run.sh` file? Please add it to `files` directory and use a different name, something like `run-java.sh`. Thanks

**Comment by sefroberg** [comment]
@phracek please try running the tests again. The run.sh is in the xpaas test repo. I just merged the change into the master branch so this PR should work correctly now.

**Comment by phracek** [comment]
It looks like test is passing:

```bash
            "[2023-08-17 03:03:53,758] INFO - *** DockerImageTest#testExposedTcpPorts() succeeded after 0:00:00.001. ***",
            "[INFO] ",
            "[INFO] Results:",
            "[INFO] ",
            "[WARNING] Tests run: 33, Failures: 0, Errors: 0, Skipped: 1",
            "[INFO] ",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Reactor Summary:",
            "[INFO] ",
            "[INFO] xPaaS Test Suite 4.1.0 ............................. SUCCESS [  0.370 s]",
            "[INFO] xPaaS Test Suite :: OpenJDK 4.1.0 .................. SUCCESS [24:38 min]",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] BUILD SUCCESS",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Total time: 24:39 min",
            "[INFO] Finished at: 2023-08-17T03:03:53-04:00",
            "[INFO] ------------------------------------------------------------------------"
```

**Review by phracek — APPROVED** [review]

**Pull request merged**
