### PR TITLE
Testing Java 8 and 11 containers under OpenShift

### PR DESCRIPTION
**Pull request by phracek**
This pull request brings a new tests for Java 8 and Java 11 containers under OpenShift.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
Test for version 8:

```bash
TASK [Run test for OpenJDK 8 container] *********************************************************************************************
changed: [localhost]

TASK [debug] ************************************************************************************************************************
ok: [localhost] => {
    "command_out": {
        "changed": true,
        "failed": false,
        "rc": 0,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "[INFO] Scanning for projects...\n[INFO] ------------------------------------------------------------------------\n[INFO] Reactor Build Order:\n[INFO] \n[INFO] xPaaS Test Suite                                                   [pom]\n[INFO] xPaaS Test Suite :: OpenJDK                                        [jar]\n[INFO] \n[INFO] --------------------< com.redhat.xpaas.qe:openjdk >---------------------\n[INFO] Building xPaaS Test Suite 3.1.0-SNAPSHOT                           [1/2]\n[INFO] --------------------------------[ pom ]---------------------------------\n[INFO] \n[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ openjdk ---\n[INFO] \n[INFO] ------------------< com.redhat.xpaas.qe:test-openjdk >------------------\n[INFO] Building xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT                [2/2]\n[INFO] --------------------------------[ jar ]---------------------------------\n[INFO] \n[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ test-openjdk ---\n[INFO] \n[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-openjdk ---\n[INFO] Using 'UTF-8' encoding to copy filtered resources.\n[INFO] skip non existing resourceDirectory /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/main/resources\n[INFO] \n[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ test-openjdk ---\n[INFO] No sources to compile\n[INFO] \n[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-openjdk ---\n[INFO] Using 'UTF-8' encoding to copy filtered resources.\n[INFO] Copying 52 resources\n[INFO] \n[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ test-openjdk ---\n[INFO] Changes detected - recompiling the module!\n[INFO] Compiling 63 source files to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/test-classes\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Some input files use or override a deprecated API.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Recompile with -Xlint:deprecation for details.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Some input files use unchecked or unsafe operations.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Recompile with -Xlint:unchecked for details.\n[INFO] \n[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ test-openjdk ---\n[INFO] \n[INFO] -------------------------------------------------------\n[INFO]  T E S T S\n[INFO] -------------------------------------------------------\n[INFO] \n[INFO] Results:\n[INFO] \n[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0\n[INFO] \n[ERROR] There are test failures.\n\nPlease refer to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/surefire-reports for the individual test results.\nPlease refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.\nThere was an error in the forked process\nName must be provided.\norg.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process\nName must be provided.\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)\n\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)\n\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)\n\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)\n\tat org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)\n\tat org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)\n\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)\n\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)\n\tat org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)\n\tat org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)\n\tat org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)\n\tat org.apache.maven.cli.MavenCli.main(MavenCli.java:192)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)\n\n[INFO] ------------------------------------------------------------------------\n[INFO] Reactor Summary:\n[INFO] \n[INFO] xPaaS Test Suite 3.1.0-SNAPSHOT .................... SUCCESS [  0.489 s]\n[INFO] xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT ......... SUCCESS [ 13.534 s]\n[INFO] ------------------------------------------------------------------------\n[INFO] BUILD SUCCESS\n[INFO] ------------------------------------------------------------------------\n[INFO] Total time: 14.280 s\n[INFO] Finished at: 2020-08-17T09:15:52Z\n[INFO] ------------------------------------------------------------------------\n",
        "stdout_lines": [
            "[INFO] Scanning for projects...",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Reactor Build Order:",
            "[INFO] ",
            "[INFO] xPaaS Test Suite                                                   [pom]",
            "[INFO] xPaaS Test Suite :: OpenJDK                                        [jar]",
            "[INFO] ",
            "[INFO] --------------------< com.redhat.xpaas.qe:openjdk >---------------------",
            "[INFO] Building xPaaS Test Suite 3.1.0-SNAPSHOT                           [1/2]",
            "[INFO] --------------------------------[ pom ]---------------------------------",
            "[INFO] ",
            "[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ openjdk ---",
            "[INFO] ",
            "[INFO] ------------------< com.redhat.xpaas.qe:test-openjdk >------------------",
            "[INFO] Building xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT                [2/2]",
            "[INFO] --------------------------------[ jar ]---------------------------------",
            "[INFO] ",
            "[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ test-openjdk ---",
            "[INFO] ",
            "[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-openjdk ---",
            "[INFO] Using 'UTF-8' encoding to copy filtered resources.",
            "[INFO] skip non existing resourceDirectory /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/main/resources",
            "[INFO] ",
            "[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ test-openjdk ---",
            "[INFO] No sources to compile",
            "[INFO] ",
            "[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-openjdk ---",
            "[INFO] Using 'UTF-8' encoding to copy filtered resources.",
            "[INFO] Copying 52 resources",
            "[INFO] ",
            "[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ test-openjdk ---",
            "[INFO] Changes detected - recompiling the module!",
            "[INFO] Compiling 63 source files to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/test-classes",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Some input files use or override a deprecated API.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Recompile with -Xlint:deprecation for details.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Some input files use unchecked or unsafe operations.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Recompile with -Xlint:unchecked for details.",
            "[INFO] ",
            "[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ test-openjdk ---",
            "[INFO] ",
            "[INFO] -------------------------------------------------------",
            "[INFO]  T E S T S",
            "[INFO] -------------------------------------------------------",
            "[INFO] ",
            "[INFO] Results:",
            "[INFO] ",
            "[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0",
            "[INFO] ",
            "[ERROR] There are test failures.",
            "",
            "Please refer to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/surefire-reports for the individual test results.",
            "Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.",
            "There was an error in the forked process",
            "Name must be provided.",
            "org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process",
            "Name must be provided.",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)",
            "\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)",
            "\tat org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)",
            "\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)",
            "\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)",
            "\tat org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)",
            "\tat org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)",
            "\tat org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)",
            "\tat org.apache.maven.cli.MavenCli.main(MavenCli.java:192)",
            "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "\tat java.lang.reflect.Method.invoke(Method.java:498)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)",
            "",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Reactor Summary:",
            "[INFO] ",
            "[INFO] xPaaS Test Suite 3.1.0-SNAPSHOT .................... SUCCESS [  0.489 s]",
            "[INFO] xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT ......... SUCCESS [ 13.534 s]",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] BUILD SUCCESS",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Total time: 14.280 s",
            "[INFO] Finished at: 2020-08-17T09:15:52Z",
            "[INFO] ------------------------------------------------------------------------"
        ]
    }
}
```


Test for version 11:
```bash
TASK [Run test for OpenJDK 11 container] ********************************************************************************************
changed: [localhost]

TASK [debug] ************************************************************************************************************************
ok: [localhost] => {
    "command_out": {
        "changed": true,
        "failed": false,
        "rc": 0,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "[INFO] Scanning for projects...\n[INFO] ------------------------------------------------------------------------\n[INFO] Reactor Build Order:\n[INFO] \n[INFO] xPaaS Test Suite                                                   [pom]\n[INFO] xPaaS Test Suite :: OpenJDK                                        [jar]\n[INFO] \n[INFO] --------------------< com.redhat.xpaas.qe:openjdk >---------------------\n[INFO] Building xPaaS Test Suite 3.1.0-SNAPSHOT                           [1/2]\n[INFO] --------------------------------[ pom ]---------------------------------\n[INFO] \n[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ openjdk ---\n[INFO] \n[INFO] ------------------< com.redhat.xpaas.qe:test-openjdk >------------------\n[INFO] Building xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT                [2/2]\n[INFO] --------------------------------[ jar ]---------------------------------\n[INFO] \n[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ test-openjdk ---\n[INFO] \n[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-openjdk ---\n[INFO] Using 'UTF-8' encoding to copy filtered resources.\n[INFO] skip non existing resourceDirectory /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/main/resources\n[INFO] \n[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ test-openjdk ---\n[INFO] No sources to compile\n[INFO] \n[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-openjdk ---\n[INFO] Using 'UTF-8' encoding to copy filtered resources.\n[INFO] Copying 52 resources\n[INFO] \n[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ test-openjdk ---\n[INFO] Changes detected - recompiling the module!\n[INFO] Compiling 63 source files to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/test-classes\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Some input files use or override a deprecated API.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Recompile with -Xlint:deprecation for details.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Some input files use unchecked or unsafe operations.\n[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Recompile with -Xlint:unchecked for details.\n[INFO] \n[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ test-openjdk ---\n[INFO] \n[INFO] -------------------------------------------------------\n[INFO]  T E S T S\n[INFO] -------------------------------------------------------\n[INFO] \n[INFO] Results:\n[INFO] \n[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0\n[INFO] \n[ERROR] There are test failures.\n\nPlease refer to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/surefire-reports for the individual test results.\nPlease refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.\nThere was an error in the forked process\nName must be provided.\norg.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process\nName must be provided.\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)\n\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)\n\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)\n\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)\n\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)\n\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)\n\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)\n\tat org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)\n\tat org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)\n\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)\n\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)\n\tat org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)\n\tat org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)\n\tat org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)\n\tat org.apache.maven.cli.MavenCli.main(MavenCli.java:192)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)\n\tat org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)\n\n[INFO] ------------------------------------------------------------------------\n[INFO] Reactor Summary:\n[INFO] \n[INFO] xPaaS Test Suite 3.1.0-SNAPSHOT .................... SUCCESS [  0.500 s]\n[INFO] xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT ......... SUCCESS [ 13.011 s]\n[INFO] ------------------------------------------------------------------------\n[INFO] BUILD SUCCESS\n[INFO] ------------------------------------------------------------------------\n[INFO] Total time: 13.765 s\n[INFO] Finished at: 2020-08-17T09:16:11Z\n[INFO] ------------------------------------------------------------------------\n",
        "stdout_lines": [
            "[INFO] Scanning for projects...",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Reactor Build Order:",
            "[INFO] ",
            "[INFO] xPaaS Test Suite                                                   [pom]",
            "[INFO] xPaaS Test Suite :: OpenJDK                                        [jar]",
            "[INFO] ",
            "[INFO] --------------------< com.redhat.xpaas.qe:openjdk >---------------------",
            "[INFO] Building xPaaS Test Suite 3.1.0-SNAPSHOT                           [1/2]",
            "[INFO] --------------------------------[ pom ]---------------------------------",
            "[INFO] ",
            "[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ openjdk ---",
            "[INFO] ",
            "[INFO] ------------------< com.redhat.xpaas.qe:test-openjdk >------------------",
            "[INFO] Building xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT                [2/2]",
            "[INFO] --------------------------------[ jar ]---------------------------------",
            "[INFO] ",
            "[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ test-openjdk ---",
            "[INFO] ",
            "[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-openjdk ---",
            "[INFO] Using 'UTF-8' encoding to copy filtered resources.",
            "[INFO] skip non existing resourceDirectory /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/main/resources",
            "[INFO] ",
            "[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ test-openjdk ---",
            "[INFO] No sources to compile",
            "[INFO] ",
            "[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-openjdk ---",
            "[INFO] Using 'UTF-8' encoding to copy filtered resources.",
            "[INFO] Copying 52 resources",
            "[INFO] ",
            "[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ test-openjdk ---",
            "[INFO] Changes detected - recompiling the module!",
            "[INFO] Compiling 63 source files to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/test-classes",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Some input files use or override a deprecated API.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/prometheus/AbstractPrometheusTest.java: Recompile with -Xlint:deprecation for details.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Some input files use unchecked or unsafe operations.",
            "[INFO] /tmp/rhscl_openshift_dir/openjdk/test-openjdk/src/test/java/com/redhat/xpaas/openjdk/ha/AbstractCounterTest.java: Recompile with -Xlint:unchecked for details.",
            "[INFO] ",
            "[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ test-openjdk ---",
            "[INFO] ",
            "[INFO] -------------------------------------------------------",
            "[INFO]  T E S T S",
            "[INFO] -------------------------------------------------------",
            "[INFO] ",
            "[INFO] Results:",
            "[INFO] ",
            "[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0",
            "[INFO] ",
            "[ERROR] There are test failures.",
            "",
            "Please refer to /tmp/rhscl_openshift_dir/openjdk/test-openjdk/target/surefire-reports for the individual test results.",
            "Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.",
            "There was an error in the forked process",
            "Name must be provided.",
            "org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process",
            "Name must be provided.",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)",
            "\tat org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)",
            "\tat org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)",
            "\tat org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)",
            "\tat org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)",
            "\tat org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)",
            "\tat org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)",
            "\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)",
            "\tat org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)",
            "\tat org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)",
            "\tat org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)",
            "\tat org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)",
            "\tat org.apache.maven.cli.MavenCli.main(MavenCli.java:192)",
            "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "\tat java.lang.reflect.Method.invoke(Method.java:498)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)",
            "\tat org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)",
            "",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Reactor Summary:",
            "[INFO] ",
            "[INFO] xPaaS Test Suite 3.1.0-SNAPSHOT .................... SUCCESS [  0.500 s]",
            "[INFO] xPaaS Test Suite :: OpenJDK 3.1.0-SNAPSHOT ......... SUCCESS [ 13.011 s]",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] BUILD SUCCESS",
            "[INFO] ------------------------------------------------------------------------",
            "[INFO] Total time: 13.765 s",
            "[INFO] Finished at: 2020-08-17T09:16:11Z",
            "[INFO] ------------------------------------------------------------------------"
        ]
    }
}
```

**Comment by phracek** [comment]
@ryankwilliams Here is a test suite for Java 8 and Java 11 containers.

**Comment by judovana** [comment]
Hi! Deepst thanks for the work.  Whole team heavily appreciate.
Unluckily the runs are false. The output looks differently when successful and runs about 10 minutes.

**Comment by phracek** [comment]
The output of this test suite is stored in usual location `/tmp/rhscl_openshift_dir`:

The files look like:
```bash
$ ls -la /tmp/rhscl_openshift_dir
total 432
drwxr-xr-x  11 phracek  wheel    352 Aug 17 19:56 .
drwxrwxrwt  48 root     wheel   1536 Aug 17 19:48 ..
-rw-r--r--   1 phracek  staff  39217 Aug 17 19:56 java-11-TEST-com.redhat.xpaas.openjdk.image.DockerImageTest.xml
-rw-r--r--   1 phracek  staff  33589 Aug 17 19:56 java-11-TEST-com.redhat.xpaas.openjdk.maven.MavenJavaArgsTest.xml
-rw-r--r--   1 phracek  staff  17156 Aug 17 19:56 java-11-TEST-com.redhat.xpaas.openjdk.opts.JavaMemoryOptionsTest.xml
-rw-r--r--   1 phracek  staff  16703 Aug 17 19:56 java-11-TEST-com.redhat.xpaas.openjdk.s2i.springboot.SpringBootBuildTest.xml
-rw-r--r--   1 phracek  staff  17447 Aug 17 19:22 java-8-TEST-com.redhat.xpaas.openjdk.image.DockerImageTest.xml
-rw-r--r--   1 phracek  staff  33586 Aug 17 19:22 java-8-TEST-com.redhat.xpaas.openjdk.maven.MavenJavaArgsTest.xml
-rw-r--r--   1 phracek  staff  17155 Aug 17 19:22 java-8-TEST-com.redhat.xpaas.openjdk.opts.JavaMemoryOptionsTest.xml
-rw-r--r--   1 phracek  staff  16701 Aug 17 19:22 java-8-TEST-com.redhat.xpaas.openjdk.s2i.springboot.SpringBootBuildTest.xml
$
```
where each file begins with:

```bash
$ cat /tmp/rhscl_openshift_dir/java-11-TEST-com.redhat.xpaas.openjdk.image.DockerImageTest.xml | head -n 2
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="com.redhat.xpaas.openjdk.image.DockerImageTest" time="29.813" tests="11" errors="0" skipped="0" failures="2">
$
```

**Comment by judovana** [comment]
Looks great!
Does it mean, that the jdk8 and jdk11 are run in single run? It would be better to split them to two runs. But I' m far from insisting.
Thanx a lot!!!

**Comment by phracek** [comment]
@judovana No, jdk8 and jdk11 are run in separated runs.
In the first case, GitLab repository is cloned, then the configuration file is modified and tests are executed.
As soon as tests are finished, then repository is deleted and the other runs begins with the same steps as previous one.

**Comment by judovana** [comment]
Thanx!

**Comment by judovana** [comment]
TY!

**Pull request merged**
